version: '3.9'

services:
  rf4-backend:
    image: polarsnowleopard/rf4-backend:latest
    container_name: rf4-backend
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - static_volume:/app/static
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=rf4.settings

volumes:
  static_volume:
