version: '3.9'

services:
  rf4-backend:
    build: .
    container_name: rf4-backend
    restart: always
    ports:
      - "9999:9999"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=rf4.settings
    command: python -m gunicorn rf4.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:9999

volumes:
  static_volume:
