# Generated by Django 5.2 on 2025-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('fish_class', models.CharField(max_length=50)),
                ('rare_weight', models.CharField(max_length=50)),
                ('super_rare_weight', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
