# Generated by Django 5.2 on 2025-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='type',
        ),
        migrations.AlterField(
            model_name='fish',
            name='description',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='fish_class',
            field=models.CharField(max_length=50, verbose_name='稀有度'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='img',
            field=models.CharField(max_length=255, verbose_name='鱼的图片'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称（种类）'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='rare_weight',
            field=models.CharField(max_length=50, verbose_name='上星重量'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='super_rare_weight',
            field=models.CharField(max_length=50, verbose_name='蓝冠重量'),
        ),
    ]
