# Generated by Django 5.2 on 2025-04-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_remove_fish_type_alter_fish_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='fish_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='稀有度'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='鱼的图片'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='名称（种类）'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='rare_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上星重量'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='super_rare_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='蓝冠重量'),
        ),
    ]
