# Generated by Django 5.2 on 2025-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_alter_fish_description_alter_fish_fish_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='名称（种类）'),
        ),
    ]
